name: Publish snapshot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cross:
    strategy:
      fail-fast: false
      matrix:
        include:
          - TARGET: x86_64-pc-windows-msvc
            OS: windows-latest
          - TARGET: aarch64-apple-darwin
            OS: macos-latest
          - TARGET: x86_64-unknown-linux-gnu
            OS: ubuntu-22.04
    runs-on: ${{ matrix.OS }}
    env:
      MILL_RUST_TARGET: ${{ matrix.TARGET }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.TARGET }}
          override: true

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - run: chmod +x millw

      - run: ./millw fastbloomjvm.compileNative

      - uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.TARGET }}
          path: out/fastbloomjvm/compileNative.dest/native/

      - run: ls -R out/fastbloomjvm/compileNative.dest/native/

  deploy:
    needs: cross
    runs-on: ubuntu-22.04
    env:
      MILL_RUST_TARGET: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: result-x86_64-unknown-linux-gnu
          path: library/native/

      - run: chmod +x millw
      - run: ./millw fastbloomjvm.compileNative
      - run: ls -R library/native/
      - run: ./millw fastbloomjvm.jar
      - run: ls -R library/native/